package charset

// collationList is the list of collation
var collationList = []*Collation{
	{
		Name:      "big5_chinese_ci",
		Charset:   "big5",
		ID:        1,
		IsDefault: true,
		Sortlen:   1,
	},
	{
		Name:      "big5_bin",
		Charset:   "big5",
		ID:        84,
		IsDefault: false,
		Sortlen:   1,
	},
	{
		Name:      "dec8_swedish_ci",
		Charset:   "dec8",
		ID:        3,
		IsDefault: true,
		Sortlen:   1,
	},
	{
		Name:      "dec8_bin",
		Charset:   "dec8",
		ID:        69,
		IsDefault: false,
		Sortlen:   1,
	},
	{
		Name:      "cp850_general_ci",
		Charset:   "cp850",
		ID:        4,
		IsDefault: true,
		Sortlen:   1,
	},
	{
		Name:      "cp850_bin",
		Charset:   "cp850",
		ID:        80,
		IsDefault: false,
		Sortlen:   1,
	},
	{
		Name:      "hp8_english_ci",
		Charset:   "hp8",
		ID:        6,
		IsDefault: true,
		Sortlen:   1,
	},
	{
		Name:      "hp8_bin",
		Charset:   "hp8",
		ID:        72,
		IsDefault: false,
		Sortlen:   1,
	},
	{
		Name:      "koi8r_general_ci",
		Charset:   "koi8r",
		ID:        7,
		IsDefault: true,
		Sortlen:   1,
	},
	{
		Name:      "koi8r_bin",
		Charset:   "koi8r",
		ID:        74,
		IsDefault: false,
		Sortlen:   1,
	},
	{
		Name:      "latin1_german1_ci",
		Charset:   "latin1",
		ID:        5,
		IsDefault: false,
		Sortlen:   1,
	},
	{
		Name:      "latin1_swedish_ci",
		Charset:   "latin1",
		ID:        8,
		IsDefault: true,
		Sortlen:   1,
	},
	{
		Name:      "latin1_danish_ci",
		Charset:   "latin1",
		ID:        15,
		IsDefault: false,
		Sortlen:   1,
	},
	{
		Name:      "latin1_german2_ci",
		Charset:   "latin1",
		ID:        31,
		IsDefault: false,
		Sortlen:   2,
	},
	{
		Name:      "latin1_bin",
		Charset:   "latin1",
		ID:        47,
		IsDefault: false,
		Sortlen:   1,
	},
	{
		Name:      "latin1_general_ci",
		Charset:   "latin1",
		ID:        48,
		IsDefault: false,
		Sortlen:   1,
	},
	{
		Name:      "latin1_general_cs",
		Charset:   "latin1",
		ID:        49,
		IsDefault: false,
		Sortlen:   1,
	},
	{
		Name:      "latin1_spanish_ci",
		Charset:   "latin1",
		ID:        94,
		IsDefault: false,
		Sortlen:   1,
	},
	{
		Name:      "latin2_czech_cs",
		Charset:   "latin2",
		ID:        2,
		IsDefault: false,
		Sortlen:   4,
	},
	{
		Name:      "latin2_general_ci",
		Charset:   "latin2",
		ID:        9,
		IsDefault: true,
		Sortlen:   1,
	},
	{
		Name:      "latin2_hungarian_ci",
		Charset:   "latin2",
		ID:        21,
		IsDefault: false,
		Sortlen:   1,
	},
	{
		Name:      "latin2_croatian_ci",
		Charset:   "latin2",
		ID:        27,
		IsDefault: false,
		Sortlen:   1,
	},
	{
		Name:      "latin2_bin",
		Charset:   "latin2",
		ID:        77,
		IsDefault: false,
		Sortlen:   1,
	},
	{
		Name:      "swe7_swedish_ci",
		Charset:   "swe7",
		ID:        10,
		IsDefault: true,
		Sortlen:   1,
	},
	{
		Name:      "swe7_bin",
		Charset:   "swe7",
		ID:        82,
		IsDefault: false,
		Sortlen:   1,
	},
	{
		Name:      "ascii_general_ci",
		Charset:   "ascii",
		ID:        11,
		IsDefault: true,
		Sortlen:   1,
	},
	{
		Name:      "ascii_bin",
		Charset:   "ascii",
		ID:        65,
		IsDefault: false,
		Sortlen:   1,
	},
	{
		Name:      "ujis_japanese_ci",
		Charset:   "ujis",
		ID:        12,
		IsDefault: true,
		Sortlen:   1,
	},
	{
		Name:      "ujis_bin",
		Charset:   "ujis",
		ID:        91,
		IsDefault: false,
		Sortlen:   1,
	},
	{
		Name:      "sjis_japanese_ci",
		Charset:   "sjis",
		ID:        13,
		IsDefault: true,
		Sortlen:   1,
	},
	{
		Name:      "sjis_bin",
		Charset:   "sjis",
		ID:        88,
		IsDefault: false,
		Sortlen:   1,
	},
	{
		Name:      "hebrew_general_ci",
		Charset:   "hebrew",
		ID:        16,
		IsDefault: true,
		Sortlen:   1,
	},
	{
		Name:      "hebrew_bin",
		Charset:   "hebrew",
		ID:        71,
		IsDefault: false,
		Sortlen:   1,
	},
	{
		Name:      "tis620_thai_ci",
		Charset:   "tis620",
		ID:        18,
		IsDefault: true,
		Sortlen:   4,
	},
	{
		Name:      "tis620_bin",
		Charset:   "tis620",
		ID:        89,
		IsDefault: false,
		Sortlen:   1,
	},
	{
		Name:      "euckr_korean_ci",
		Charset:   "euckr",
		ID:        19,
		IsDefault: true,
		Sortlen:   1,
	},
	{
		Name:      "euckr_bin",
		Charset:   "euckr",
		ID:        85,
		IsDefault: false,
		Sortlen:   1,
	},
	{
		Name:      "koi8u_general_ci",
		Charset:   "koi8u",
		ID:        22,
		IsDefault: true,
		Sortlen:   1,
	},
	{
		Name:      "koi8u_bin",
		Charset:   "koi8u",
		ID:        75,
		IsDefault: false,
		Sortlen:   1,
	},
	{
		Name:      "gb2312_chinese_ci",
		Charset:   "gb2312",
		ID:        24,
		IsDefault: true,
		Sortlen:   1,
	},
	{
		Name:      "gb2312_bin",
		Charset:   "gb2312",
		ID:        86,
		IsDefault: false,
		Sortlen:   1,
	},
	{
		Name:      "greek_general_ci",
		Charset:   "greek",
		ID:        25,
		IsDefault: true,
		Sortlen:   1,
	},
	{
		Name:      "greek_bin",
		Charset:   "greek",
		ID:        70,
		IsDefault: false,
		Sortlen:   1,
	},
	{
		Name:      "cp1250_general_ci",
		Charset:   "cp1250",
		ID:        26,
		IsDefault: true,
		Sortlen:   1,
	},
	{
		Name:      "cp1250_czech_cs",
		Charset:   "cp1250",
		ID:        34,
		IsDefault: false,
		Sortlen:   2,
	},
	{
		Name:      "cp1250_croatian_ci",
		Charset:   "cp1250",
		ID:        44,
		IsDefault: false,
		Sortlen:   1,
	},
	{
		Name:      "cp1250_bin",
		Charset:   "cp1250",
		ID:        66,
		IsDefault: false,
		Sortlen:   1,
	},
	{
		Name:      "cp1250_polish_ci",
		Charset:   "cp1250",
		ID:        99,
		IsDefault: false,
		Sortlen:   1,
	},
	{
		Name:      "gbk_chinese_ci",
		Charset:   "gbk",
		ID:        28,
		IsDefault: true,
		Sortlen:   1,
	},
	{
		Name:      "gbk_bin",
		Charset:   "gbk",
		ID:        87,
		IsDefault: false,
		Sortlen:   1,
	},
	{
		Name:      "latin5_turkish_ci",
		Charset:   "latin5",
		ID:        30,
		IsDefault: true,
		Sortlen:   1,
	},
	{
		Name:      "latin5_bin",
		Charset:   "latin5",
		ID:        78,
		IsDefault: false,
		Sortlen:   1,
	},
	{
		Name:      "armscii8_general_ci",
		Charset:   "armscii8",
		ID:        32,
		IsDefault: true,
		Sortlen:   1,
	},
	{
		Name:      "armscii8_bin",
		Charset:   "armscii8",
		ID:        64,
		IsDefault: false,
		Sortlen:   1,
	},
	{
		Name:      "utf8_general_ci",
		Charset:   "utf8",
		ID:        33,
		IsDefault: true,
		Sortlen:   1,
	},
	{
		Name:      "utf8_bin",
		Charset:   "utf8",
		ID:        83,
		IsDefault: false,
		Sortlen:   1,
	},
	{
		Name:      "utf8_unicode_ci",
		Charset:   "utf8",
		ID:        192,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "utf8_icelandic_ci",
		Charset:   "utf8",
		ID:        193,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "utf8_latvian_ci",
		Charset:   "utf8",
		ID:        194,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "utf8_romanian_ci",
		Charset:   "utf8",
		ID:        195,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "utf8_slovenian_ci",
		Charset:   "utf8",
		ID:        196,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "utf8_polish_ci",
		Charset:   "utf8",
		ID:        197,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "utf8_estonian_ci",
		Charset:   "utf8",
		ID:        198,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "utf8_spanish_ci",
		Charset:   "utf8",
		ID:        199,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "utf8_swedish_ci",
		Charset:   "utf8",
		ID:        200,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "utf8_turkish_ci",
		Charset:   "utf8",
		ID:        201,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "utf8_czech_ci",
		Charset:   "utf8",
		ID:        202,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "utf8_danish_ci",
		Charset:   "utf8",
		ID:        203,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "utf8_lithuanian_ci",
		Charset:   "utf8",
		ID:        204,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "utf8_slovak_ci",
		Charset:   "utf8",
		ID:        205,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "utf8_spanish2_ci",
		Charset:   "utf8",
		ID:        206,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "utf8_roman_ci",
		Charset:   "utf8",
		ID:        207,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "utf8_persian_ci",
		Charset:   "utf8",
		ID:        208,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "utf8_esperanto_ci",
		Charset:   "utf8",
		ID:        209,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "utf8_hungarian_ci",
		Charset:   "utf8",
		ID:        210,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "utf8_sinhala_ci",
		Charset:   "utf8",
		ID:        211,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "utf8_german2_ci",
		Charset:   "utf8",
		ID:        212,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "utf8_croatian_ci",
		Charset:   "utf8",
		ID:        213,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "utf8_unicode_520_ci",
		Charset:   "utf8",
		ID:        214,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "utf8_vietnamese_ci",
		Charset:   "utf8",
		ID:        215,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "utf8_general_mysql500_ci",
		Charset:   "utf8",
		ID:        223,
		IsDefault: false,
		Sortlen:   1,
	},
	{
		Name:      "ucs2_general_ci",
		Charset:   "ucs2",
		ID:        35,
		IsDefault: true,
		Sortlen:   1,
	},
	{
		Name:      "ucs2_bin",
		Charset:   "ucs2",
		ID:        90,
		IsDefault: false,
		Sortlen:   1,
	},
	{
		Name:      "ucs2_unicode_ci",
		Charset:   "ucs2",
		ID:        128,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "ucs2_icelandic_ci",
		Charset:   "ucs2",
		ID:        129,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "ucs2_latvian_ci",
		Charset:   "ucs2",
		ID:        130,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "ucs2_romanian_ci",
		Charset:   "ucs2",
		ID:        131,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "ucs2_slovenian_ci",
		Charset:   "ucs2",
		ID:        132,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "ucs2_polish_ci",
		Charset:   "ucs2",
		ID:        133,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "ucs2_estonian_ci",
		Charset:   "ucs2",
		ID:        134,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "ucs2_spanish_ci",
		Charset:   "ucs2",
		ID:        135,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "ucs2_swedish_ci",
		Charset:   "ucs2",
		ID:        136,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "ucs2_turkish_ci",
		Charset:   "ucs2",
		ID:        137,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "ucs2_czech_ci",
		Charset:   "ucs2",
		ID:        138,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "ucs2_danish_ci",
		Charset:   "ucs2",
		ID:        139,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "ucs2_lithuanian_ci",
		Charset:   "ucs2",
		ID:        140,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "ucs2_slovak_ci",
		Charset:   "ucs2",
		ID:        141,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "ucs2_spanish2_ci",
		Charset:   "ucs2",
		ID:        142,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "ucs2_roman_ci",
		Charset:   "ucs2",
		ID:        143,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "ucs2_persian_ci",
		Charset:   "ucs2",
		ID:        144,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "ucs2_esperanto_ci",
		Charset:   "ucs2",
		ID:        145,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "ucs2_hungarian_ci",
		Charset:   "ucs2",
		ID:        146,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "ucs2_sinhala_ci",
		Charset:   "ucs2",
		ID:        147,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "ucs2_german2_ci",
		Charset:   "ucs2",
		ID:        148,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "ucs2_croatian_ci",
		Charset:   "ucs2",
		ID:        149,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "ucs2_unicode_520_ci",
		Charset:   "ucs2",
		ID:        150,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "ucs2_vietnamese_ci",
		Charset:   "ucs2",
		ID:        151,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "ucs2_general_mysql500_ci",
		Charset:   "ucs2",
		ID:        159,
		IsDefault: false,
		Sortlen:   1,
	},
	{
		Name:      "cp866_general_ci",
		Charset:   "cp866",
		ID:        36,
		IsDefault: true,
		Sortlen:   1,
	},
	{
		Name:      "cp866_bin",
		Charset:   "cp866",
		ID:        68,
		IsDefault: false,
		Sortlen:   1,
	},
	{
		Name:      "keybcs2_general_ci",
		Charset:   "keybcs2",
		ID:        37,
		IsDefault: true,
		Sortlen:   1,
	},
	{
		Name:      "keybcs2_bin",
		Charset:   "keybcs2",
		ID:        73,
		IsDefault: false,
		Sortlen:   1,
	},
	{
		Name:      "macce_general_ci",
		Charset:   "macce",
		ID:        38,
		IsDefault: true,
		Sortlen:   1,
	},
	{
		Name:      "macce_bin",
		Charset:   "macce",
		ID:        43,
		IsDefault: false,
		Sortlen:   1,
	},
	{
		Name:      "macroman_general_ci",
		Charset:   "macroman",
		ID:        39,
		IsDefault: true,
		Sortlen:   1,
	},
	{
		Name:      "macroman_bin",
		Charset:   "macroman",
		ID:        53,
		IsDefault: false,
		Sortlen:   1,
	},
	{
		Name:      "cp852_general_ci",
		Charset:   "cp852",
		ID:        40,
		IsDefault: true,
		Sortlen:   1,
	},
	{
		Name:      "cp852_bin",
		Charset:   "cp852",
		ID:        81,
		IsDefault: false,
		Sortlen:   1,
	},
	{
		Name:      "latin7_estonian_cs",
		Charset:   "latin7",
		ID:        20,
		IsDefault: false,
		Sortlen:   1,
	},
	{
		Name:      "latin7_general_ci",
		Charset:   "latin7",
		ID:        41,
		IsDefault: true,
		Sortlen:   1,
	},
	{
		Name:      "latin7_general_cs",
		Charset:   "latin7",
		ID:        42,
		IsDefault: false,
		Sortlen:   1,
	},
	{
		Name:      "latin7_bin",
		Charset:   "latin7",
		ID:        79,
		IsDefault: false,
		Sortlen:   1,
	},
	{
		Name:      "utf8mb4_general_ci",
		Charset:   "utf8mb4",
		ID:        45,
		IsDefault: true,
		Sortlen:   1,
	},
	{
		Name:      "utf8mb4_bin",
		Charset:   "utf8mb4",
		ID:        46,
		IsDefault: false,
		Sortlen:   1,
	},
	{
		Name:      "utf8mb4_unicode_ci",
		Charset:   "utf8mb4",
		ID:        224,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "utf8mb4_icelandic_ci",
		Charset:   "utf8mb4",
		ID:        225,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "utf8mb4_latvian_ci",
		Charset:   "utf8mb4",
		ID:        226,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "utf8mb4_romanian_ci",
		Charset:   "utf8mb4",
		ID:        227,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "utf8mb4_slovenian_ci",
		Charset:   "utf8mb4",
		ID:        228,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "utf8mb4_polish_ci",
		Charset:   "utf8mb4",
		ID:        229,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "utf8mb4_estonian_ci",
		Charset:   "utf8mb4",
		ID:        230,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "utf8mb4_spanish_ci",
		Charset:   "utf8mb4",
		ID:        231,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "utf8mb4_swedish_ci",
		Charset:   "utf8mb4",
		ID:        232,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "utf8mb4_turkish_ci",
		Charset:   "utf8mb4",
		ID:        233,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "utf8mb4_czech_ci",
		Charset:   "utf8mb4",
		ID:        234,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "utf8mb4_danish_ci",
		Charset:   "utf8mb4",
		ID:        235,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "utf8mb4_lithuanian_ci",
		Charset:   "utf8mb4",
		ID:        236,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "utf8mb4_slovak_ci",
		Charset:   "utf8mb4",
		ID:        237,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "utf8mb4_spanish2_ci",
		Charset:   "utf8mb4",
		ID:        238,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "utf8mb4_roman_ci",
		Charset:   "utf8mb4",
		ID:        239,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "utf8mb4_persian_ci",
		Charset:   "utf8mb4",
		ID:        240,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "utf8mb4_esperanto_ci",
		Charset:   "utf8mb4",
		ID:        241,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "utf8mb4_hungarian_ci",
		Charset:   "utf8mb4",
		ID:        242,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "utf8mb4_sinhala_ci",
		Charset:   "utf8mb4",
		ID:        243,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "utf8mb4_german2_ci",
		Charset:   "utf8mb4",
		ID:        244,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "utf8mb4_croatian_ci",
		Charset:   "utf8mb4",
		ID:        245,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "utf8mb4_unicode_520_ci",
		Charset:   "utf8mb4",
		ID:        246,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "utf8mb4_vietnamese_ci",
		Charset:   "utf8mb4",
		ID:        247,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "cp1251_bulgarian_ci",
		Charset:   "cp1251",
		ID:        14,
		IsDefault: false,
		Sortlen:   1,
	},
	{
		Name:      "cp1251_ukrainian_ci",
		Charset:   "cp1251",
		ID:        23,
		IsDefault: false,
		Sortlen:   1,
	},
	{
		Name:      "cp1251_bin",
		Charset:   "cp1251",
		ID:        50,
		IsDefault: false,
		Sortlen:   1,
	},
	{
		Name:      "cp1251_general_ci",
		Charset:   "cp1251",
		ID:        51,
		IsDefault: true,
		Sortlen:   1,
	},
	{
		Name:      "cp1251_general_cs",
		Charset:   "cp1251",
		ID:        52,
		IsDefault: false,
		Sortlen:   1,
	},
	{
		Name:      "utf16_general_ci",
		Charset:   "utf16",
		ID:        54,
		IsDefault: true,
		Sortlen:   1,
	},
	{
		Name:      "utf16_bin",
		Charset:   "utf16",
		ID:        55,
		IsDefault: false,
		Sortlen:   1,
	},
	{
		Name:      "utf16_unicode_ci",
		Charset:   "utf16",
		ID:        101,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "utf16_icelandic_ci",
		Charset:   "utf16",
		ID:        102,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "utf16_latvian_ci",
		Charset:   "utf16",
		ID:        103,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "utf16_romanian_ci",
		Charset:   "utf16",
		ID:        104,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "utf16_slovenian_ci",
		Charset:   "utf16",
		ID:        105,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "utf16_polish_ci",
		Charset:   "utf16",
		ID:        106,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "utf16_estonian_ci",
		Charset:   "utf16",
		ID:        107,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "utf16_spanish_ci",
		Charset:   "utf16",
		ID:        108,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "utf16_swedish_ci",
		Charset:   "utf16",
		ID:        109,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "utf16_turkish_ci",
		Charset:   "utf16",
		ID:        110,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "utf16_czech_ci",
		Charset:   "utf16",
		ID:        111,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "utf16_danish_ci",
		Charset:   "utf16",
		ID:        112,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "utf16_lithuanian_ci",
		Charset:   "utf16",
		ID:        113,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "utf16_slovak_ci",
		Charset:   "utf16",
		ID:        114,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "utf16_spanish2_ci",
		Charset:   "utf16",
		ID:        115,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "utf16_roman_ci",
		Charset:   "utf16",
		ID:        116,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "utf16_persian_ci",
		Charset:   "utf16",
		ID:        117,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "utf16_esperanto_ci",
		Charset:   "utf16",
		ID:        118,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "utf16_hungarian_ci",
		Charset:   "utf16",
		ID:        119,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "utf16_sinhala_ci",
		Charset:   "utf16",
		ID:        120,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "utf16_german2_ci",
		Charset:   "utf16",
		ID:        121,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "utf16_croatian_ci",
		Charset:   "utf16",
		ID:        122,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "utf16_unicode_520_ci",
		Charset:   "utf16",
		ID:        123,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "utf16_vietnamese_ci",
		Charset:   "utf16",
		ID:        124,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "utf16le_general_ci",
		Charset:   "utf16le",
		ID:        56,
		IsDefault: true,
		Sortlen:   1,
	},
	{
		Name:      "utf16le_bin",
		Charset:   "utf16le",
		ID:        62,
		IsDefault: false,
		Sortlen:   1,
	},
	{
		Name:      "cp1256_general_ci",
		Charset:   "cp1256",
		ID:        57,
		IsDefault: true,
		Sortlen:   1,
	},
	{
		Name:      "cp1256_bin",
		Charset:   "cp1256",
		ID:        67,
		IsDefault: false,
		Sortlen:   1,
	},
	{
		Name:      "cp1257_lithuanian_ci",
		Charset:   "cp1257",
		ID:        29,
		IsDefault: false,
		Sortlen:   1,
	},
	{
		Name:      "cp1257_bin",
		Charset:   "cp1257",
		ID:        58,
		IsDefault: false,
		Sortlen:   1,
	},
	{
		Name:      "cp1257_general_ci",
		Charset:   "cp1257",
		ID:        59,
		IsDefault: true,
		Sortlen:   1,
	},
	{
		Name:      "utf32_general_ci",
		Charset:   "utf32",
		ID:        60,
		IsDefault: true,
		Sortlen:   1,
	},
	{
		Name:      "utf32_bin",
		Charset:   "utf32",
		ID:        61,
		IsDefault: false,
		Sortlen:   1,
	},
	{
		Name:      "utf32_unicode_ci",
		Charset:   "utf32",
		ID:        160,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "utf32_icelandic_ci",
		Charset:   "utf32",
		ID:        161,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "utf32_latvian_ci",
		Charset:   "utf32",
		ID:        162,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "utf32_romanian_ci",
		Charset:   "utf32",
		ID:        163,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "utf32_slovenian_ci",
		Charset:   "utf32",
		ID:        164,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "utf32_polish_ci",
		Charset:   "utf32",
		ID:        165,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "utf32_estonian_ci",
		Charset:   "utf32",
		ID:        166,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "utf32_spanish_ci",
		Charset:   "utf32",
		ID:        167,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "utf32_swedish_ci",
		Charset:   "utf32",
		ID:        168,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "utf32_turkish_ci",
		Charset:   "utf32",
		ID:        169,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "utf32_czech_ci",
		Charset:   "utf32",
		ID:        170,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "utf32_danish_ci",
		Charset:   "utf32",
		ID:        171,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "utf32_lithuanian_ci",
		Charset:   "utf32",
		ID:        172,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "utf32_slovak_ci",
		Charset:   "utf32",
		ID:        173,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "utf32_spanish2_ci",
		Charset:   "utf32",
		ID:        174,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "utf32_roman_ci",
		Charset:   "utf32",
		ID:        175,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "utf32_persian_ci",
		Charset:   "utf32",
		ID:        176,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "utf32_esperanto_ci",
		Charset:   "utf32",
		ID:        177,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "utf32_hungarian_ci",
		Charset:   "utf32",
		ID:        178,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "utf32_sinhala_ci",
		Charset:   "utf32",
		ID:        179,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "utf32_german2_ci",
		Charset:   "utf32",
		ID:        180,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "utf32_croatian_ci",
		Charset:   "utf32",
		ID:        181,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "utf32_unicode_520_ci",
		Charset:   "utf32",
		ID:        182,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "utf32_vietnamese_ci",
		Charset:   "utf32",
		ID:        183,
		IsDefault: false,
		Sortlen:   8,
	},
	{
		Name:      "binary",
		Charset:   "binary",
		ID:        63,
		IsDefault: true,
		Sortlen:   1,
	},
	{
		Name:      "geostd8_general_ci",
		Charset:   "geostd8",
		ID:        92,
		IsDefault: true,
		Sortlen:   1,
	},
	{
		Name:      "geostd8_bin",
		Charset:   "geostd8",
		ID:        93,
		IsDefault: false,
		Sortlen:   1,
	},
	{
		Name:      "cp932_japanese_ci",
		Charset:   "cp932",
		ID:        95,
		IsDefault: true,
		Sortlen:   1,
	},
	{
		Name:      "cp932_bin",
		Charset:   "cp932",
		ID:        96,
		IsDefault: false,
		Sortlen:   1,
	},
	{
		Name:      "eucjpms_japanese_ci",
		Charset:   "eucjpms",
		ID:        97,
		IsDefault: true,
		Sortlen:   1,
	},
	{
		Name:      "eucjpms_bin",
		Charset:   "eucjpms",
		ID:        98,
		IsDefault: false,
		Sortlen:   1,
	},
	{
		Name:      "gb18030_chinese_ci",
		Charset:   "gb18030",
		ID:        248,
		IsDefault: true,
		Sortlen:   2,
	},
	{
		Name:      "gb18030_bin",
		Charset:   "gb18030",
		ID:        249,
		IsDefault: false,
		Sortlen:   1,
	},
	{
		Name:      "gb18030_unicode_520_ci",
		Charset:   "gb18030",
		ID:        250,
		IsDefault: false,
		Sortlen:   8,
	},
}

// charsetList is the list of charset
var charsetList = []*Charset{
	{
		Name:             "big5",
		Description:      "Big5 Traditional Chinese",
		DefaultCollation: "big5_chinese_ci",
		MaxLength:        2,
	},
	{
		Name:             "dec8",
		Description:      "DEC West European",
		DefaultCollation: "dec8_swedish_ci",
		MaxLength:        1,
	},
	{
		Name:             "cp850",
		Description:      "DOS West European",
		DefaultCollation: "cp850_general_ci",
		MaxLength:        1,
	},
	{
		Name:             "hp8",
		Description:      "HP West European",
		DefaultCollation: "hp8_english_ci",
		MaxLength:        1,
	},
	{
		Name:             "koi8r",
		Description:      "KOI8-R Relcom Russian",
		DefaultCollation: "koi8r_general_ci",
		MaxLength:        1,
	},
	{
		Name:             "latin1",
		Description:      "cp1252 West European",
		DefaultCollation: "latin1_swedish_ci",
		MaxLength:        1,
	},
	{
		Name:             "latin2",
		Description:      "ISO 8859-2 Central European",
		DefaultCollation: "latin2_general_ci",
		MaxLength:        1,
	},
	{
		Name:             "swe7",
		Description:      "7bit Swedish",
		DefaultCollation: "swe7_swedish_ci",
		MaxLength:        1,
	},
	{
		Name:             "ascii",
		Description:      "US ASCII",
		DefaultCollation: "ascii_general_ci",
		MaxLength:        1,
	},
	{
		Name:             "ujis",
		Description:      "EUC-JP Japanese",
		DefaultCollation: "ujis_japanese_ci",
		MaxLength:        3,
	},
	{
		Name:             "sjis",
		Description:      "Shift-JIS Japanese",
		DefaultCollation: "sjis_japanese_ci",
		MaxLength:        2,
	},
	{
		Name:             "hebrew",
		Description:      "ISO 8859-8 Hebrew",
		DefaultCollation: "hebrew_general_ci",
		MaxLength:        1,
	},
	{
		Name:             "tis620",
		Description:      "TIS620 Thai",
		DefaultCollation: "tis620_thai_ci",
		MaxLength:        1,
	},
	{
		Name:             "euckr",
		Description:      "EUC-KR Korean",
		DefaultCollation: "euckr_korean_ci",
		MaxLength:        2,
	},
	{
		Name:             "koi8u",
		Description:      "KOI8-U Ukrainian",
		DefaultCollation: "koi8u_general_ci",
		MaxLength:        1,
	},
	{
		Name:             "gb2312",
		Description:      "GB2312 Simplified Chinese",
		DefaultCollation: "gb2312_chinese_ci",
		MaxLength:        2,
	},
	{
		Name:             "greek",
		Description:      "ISO 8859-7 Greek",
		DefaultCollation: "greek_general_ci",
		MaxLength:        1,
	},
	{
		Name:             "cp1250",
		Description:      "Windows Central European",
		DefaultCollation: "cp1250_general_ci",
		MaxLength:        1,
	},
	{
		Name:             "gbk",
		Description:      "GBK Simplified Chinese",
		DefaultCollation: "gbk_chinese_ci",
		MaxLength:        2,
	},
	{
		Name:             "latin5",
		Description:      "ISO 8859-9 Turkish",
		DefaultCollation: "latin5_turkish_ci",
		MaxLength:        1,
	},
	{
		Name:             "armscii8",
		Description:      "ARMSCII-8 Armenian",
		DefaultCollation: "armscii8_general_ci",
		MaxLength:        1,
	},
	{
		Name:             "utf8",
		Description:      "UTF-8 Unicode",
		DefaultCollation: "utf8_general_ci",
		MaxLength:        3,
	},
	{
		Name:             "ucs2",
		Description:      "UCS-2 Unicode",
		DefaultCollation: "ucs2_general_ci",
		MaxLength:        2,
	},
	{
		Name:             "cp866",
		Description:      "DOS Russian",
		DefaultCollation: "cp866_general_ci",
		MaxLength:        1,
	},
	{
		Name:             "keybcs2",
		Description:      "DOS Kamenicky Czech-Slovak",
		DefaultCollation: "keybcs2_general_ci",
		MaxLength:        1,
	},
	{
		Name:             "macce",
		Description:      "Mac Central European",
		DefaultCollation: "macce_general_ci",
		MaxLength:        1,
	},
	{
		Name:             "macroman",
		Description:      "Mac West European",
		DefaultCollation: "macroman_general_ci",
		MaxLength:        1,
	},
	{
		Name:             "cp852",
		Description:      "DOS Central European",
		DefaultCollation: "cp852_general_ci",
		MaxLength:        1,
	},
	{
		Name:             "latin7",
		Description:      "ISO 8859-13 Baltic",
		DefaultCollation: "latin7_general_ci",
		MaxLength:        1,
	},
	{
		Name:             "utf8mb4",
		Description:      "UTF-8 Unicode",
		DefaultCollation: "utf8mb4_general_ci",
		MaxLength:        4,
	},
	{
		Name:             "cp1251",
		Description:      "Windows Cyrillic",
		DefaultCollation: "cp1251_general_ci",
		MaxLength:        1,
	},
	{
		Name:             "utf16",
		Description:      "UTF-16 Unicode",
		DefaultCollation: "utf16_general_ci",
		MaxLength:        4,
	},
	{
		Name:             "utf16le",
		Description:      "UTF-16LE Unicode",
		DefaultCollation: "utf16le_general_ci",
		MaxLength:        4,
	},
	{
		Name:             "cp1256",
		Description:      "Windows Arabic",
		DefaultCollation: "cp1256_general_ci",
		MaxLength:        1,
	},
	{
		Name:             "cp1257",
		Description:      "Windows Baltic",
		DefaultCollation: "cp1257_general_ci",
		MaxLength:        1,
	},
	{
		Name:             "utf32",
		Description:      "UTF-32 Unicode",
		DefaultCollation: "utf32_general_ci",
		MaxLength:        4,
	},
	{
		Name:             "binary",
		Description:      "Binary pseudo charset",
		DefaultCollation: "binary",
		MaxLength:        1,
	},
	{
		Name:             "geostd8",
		Description:      "GEOSTD8 Georgian",
		DefaultCollation: "geostd8_general_ci",
		MaxLength:        1,
	},
	{
		Name:             "cp932",
		Description:      "SJIS for Windows Japanese",
		DefaultCollation: "cp932_japanese_ci",
		MaxLength:        2,
	},
	{
		Name:             "eucjpms",
		Description:      "UJIS for Windows Japanese",
		DefaultCollation: "eucjpms_japanese_ci",
		MaxLength:        3,
	},
	{
		Name:             "gb18030",
		Description:      "China National Standard GB18030",
		DefaultCollation: "gb18030_chinese_ci",
		MaxLength:        4,
	},
}
